{
 "title": "CRS cutoff metrics dashboard",
 "description": "Set up a dashboard with cool metrics to follow and visualize.",
 "time": { "from": "2023-12-31T09:34:32.770Z", "to": "2024-08-01T15:36:19.117Z" },
 "panels": [
  {
   "title": "Predicted vs actual CRS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", predicted_crs, actual_crs FROM crs_metrics LIMIT 500 "
    }
   ]
  },
  {
   "title": "RMSE of CRS",
   "type": "timeseries",
   "description": "RMSE using a rolling window of the past three months",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", rmse_crs_current FROM crs_metrics LIMIT 500 "
    }
   ]
  },
  {
   "title": "Standard deviation of error",
   "type": "timeseries",
   "description": "Standard deviation given a rolling window of 3 months prior to date.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", error_std_current FROM crs_metrics LIMIT 500 "
    }
   ]
  },
  {
   "title": "Drift CRS",
   "type": "timeseries",
   "description": "Drift of data with a rolling window of the last 3 months.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", drift_actual_crs FROM crs_metrics LIMIT 500 "
    }
   ]
  }
 ]
}